dependencies {
    implementation flexoFoundation()
    implementation flexoFoundationRm()
    implementation fmlCli()
    implementation flexoUi()
    
    implementation group: 'jline', name: 'jline', version: '2.11'

    api 'io.vertx:vertx-core:4.3.6'
    implementation 'io.vertx:vertx-web:4.3.6'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.1'
    implementation 'io.vertx:vertx-auth-htpasswd:4.3.7'


    testImplementation testUtils()
    testImplementation flexoFoundationTest()
    testImplementation 'io.vertx:vertx-unit:4.3.6'
    testImplementation 'io.vertx:vertx-junit5:4.3.6'
    testImplementation 'io.vertx:vertx-web-client:4.3.6'
    testImplementation 'org.junit.platform:junit-platform-suite:1.9.1'

}

test {
    useJUnitPlatform()
}
apply plugin: 'application'
mainClassName = "org.openflexo.http.server.OpenFlexoServer"

run {
    if ( project.hasProperty("serverArgs") ) {
        args Eval.me(serverArgs)
    }
}

